version: '3.8'

services:
  llm-webui:
    build:
      context: .
      args:
        - MODEL_URL=https://huggingface.co/Qwen/Qwen3-8B
    container_name: llm-webui-container
    ports:
      - "4444:22"
      - "8000:8000"
      - "27015:27015"
    environment:
      - OPENAI_API_BASE_URL=http://localhost:8000/v1
      - OPENAI_API_KEY=sk-fake-key
      - PORT=27015
      - DATA_DIR=/app/open-webui-data
      - VLLM_HOST=0.0.0.0
      - VLLM_PORT=8000
      - VLLM_GPU_MEMORY_UTILIZATION=0.95
      - NCCL_DEBUG=INFO
      - NCCL_IB_DISABLE=1
      - NCCL_P2P_DISABLE=1
      - VLLM_USE_V1=0
      - S6_LOGGING=1
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
    volumes:
      - ./data:/app/open-webui-data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]
    privileged: true
    ipc: host
    restart: unless-stopped
    stdin_open: true
    tty: true